### ISSUE TITLE
格式化报错

### ISSUE THREAD

**Issue by rabbull** [thrift-labs/thrift-fmt-vscode#10]
运行 Format Thrift 报错，提示
![image](https://user-images.githubusercontent.com/29354199/196502462-109a3646-cb64-41fa-88b2-9501e6b9e182.png)

**Comment by alingse** [comment]
看看是不是要升级呀。新的已经有这个 command 了 @rabbull 

https://github.com/thrift-labs/thrift-fmt-vscode/blob/main/src/web/extension.ts#L11
