### ISSUE TITLE
对齐问题

### ISSUE THREAD

**Issue by ALL-AC** [thrift-labs/thrift-fmt-vscode#19]
目前注释是单独对齐的。但是还是想问一下能否支持一些特性，如变量名称单独左对齐一列？括号内容也是左对齐一列？

**Comment by alingse** [comment]
感觉没问题，不过我在想要怎么算对齐。struct 其实 assign 的不多，我还见过有人手动对齐的

感觉也许逐字段对齐会好点，比如这种

```
struct UserData {
  1:      required  list<string>        names   = ["hello"],           // comment
  2:      required  string              name    = "hello",             // comment
  11:     required  map<string, string> namemap = {"hello": "world"},  // comment
  101:    required  i64                 id      = 0,                   // comment
}
```

得再想想 cc @ALL-AC 

比如 编号 id   required，type, name , assign, init-value, comment
全都按类型对齐。

**Comment by ALL-AC** [comment]
对的，这种逐个字段对其就是我想要的效果，非常nice。

**Comment by ALL-AC** [comment]
此外，目前所有的语法高亮都没识别(go.tag="...")这种部分。而这款格式化工具已经支持了（之前反馈过），所以想问作者有没有打算出一款语法高亮工具哈哈。或者直接在这个格式化工具里集成。

**Comment by alingse** [comment]
![截屏2023-03-16 22 57 32](https://user-images.githubusercontent.com/11423310/225666673-f4181fc5-61cf-47a9-b492-83f39392f499.png)

AI 打败人类，不需要开发啥代码了，固定描述好需求就行了。
