### ISSUE TITLE
Keep the blank line when format 格式化时保留空行

### ISSUE THREAD

**Issue by nolongerwait** [thrift-labs/thrift-fmt-vscode#20]
Is it possible to preserve blank lines (at least one line) between different fields.

Maybe we can combine multiple blank lines into one, but please keep one blank line when formatting.

Sometimes blank lines are used for visual separation.

For example:

```thrift
struct A {
    1: required string a_1,
    2: required string a_2,


    10: required string a_3,
}
```

After formatting
```thrift
struct A {
    1: required string a_1,
    2: required string a_2,

    10: required string a_3,
}
```

**Comment by alingse** [comment]
你是说 seq 有间隔的时候加空行是吗？
但是这种情况呢

```thrift
struct A {
    1: required string a_1,
    2: required string a_2,
    // 3: required string a_2,
    4: required string a_3,
}
```

这种呢？注释掉一个字段的时候 2 和 4 还需要空行么。感觉需要有一定的规则才好。
我再想想 @nolongerwait

**Comment by nolongerwait** [comment]
像这种的话本身没有空行的就不需要了。就是如果原先已经空了的，就最好留一行。（其他语言德格式化目前也是这样多个空行就格式化后留一行）因为有时候用空行分割一下，表示一堆字段的相互的抱团属性。

**Comment by alingse** [comment]
项目是基于 antlr 解析的 thrift 文件，https://github.com/antlr/grammars-v4/blob/master/thrift/Thrift.g4#L216-L218
```antlr
WS
    : (' ' | '\t' | '\r' '\n' | '\n')+ -> channel(HIDDEN)
    ;
```
会清理掉空格换行这些，
我想你的问题可以通过 `//` 空注释来解决

```
struct A {
    // 基础信息
    1: required string a_1,
    2: required string a_2,
    3: required string a_3,
    //
    4: required string a_4,
    5: required string a_5,
    //
    6: required string a_6,
    7: required string a_7,
}
```

这样是不是也能比较美观的处理。不过我也挺习惯 golang 那种方式
