### ISSUE TITLE
vscode没有识别该插件

### ISSUE THREAD

**Issue by ALL-AC** [thrift-labs/thrift-fmt-vscode#4]
提示：没有安装用于“thrift”文件的格式化程序。

**Comment by alingse** [comment]
你用 cmd + shift + p 调起 command 面板，选择 Format Thrift 看看

我还不知道怎么让 vscode 识别为 thrift 文件的格式化程序，晚上下班研究下

@ALL-AC

**Comment by alingse** [comment]
@ALL-AC 好了，试试看，我试了 ok
