### ISSUE TITLE
格式化报错

### ISSUE THREAD

**Issue by ALL-AC** [thrift-labs/thrift-fmt-vscode#7]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/49314152/180936301-f4771225-bd39-481c-a7a9-8a901ebde9e3.png">

**Comment by alingse** [comment]
可能是解析 thrift 失败了，有点尴尬，我之前拿公司的测的，你们是有 cpp include之类的么
可以看看文件大概么

**Comment by ALL-AC** [comment]
> 

没有，就是普通的thrift文件，包含了（go.tag=“”）的都格式化失败，如下：
```
struct Request {
    1: i64                                   AccountID    (go.tag = "vd:\"$>0\"")
    2: string                                SerialNumber (go.tag = "vd:\"len($)>0\"")
    253: optional bool                       FromHistory                                      // xxxx
    254: optional file.BrokerAccount  BrokerAccount                                   // xxx
    255: optional file.Base                  Base
}

**Comment by ALL-AC** [comment]
使用之前你说能支持这种go.tag格式的。此外，格式化的结果也并不满意，原本对其的代码，格式化后只剩下注释是对其的，如下：
![image](https://user-images.githubusercontent.com/49314152/181144292-ca1a3c81-15f8-49ff-a123-44dbc072db2a.png)
![image](https://user-images.githubusercontent.com/49314152/181144328-251f0630-8ce8-483a-9717-f9048d510beb.png)

**Comment by alingse** [comment]
@ALL-AC  1 第一个是 antlr4 g4 文件的语法规则没解析到 https://github.com/antlr/grammars-v4/tree/master/thrift ，我晚上看看。 
第二个是想要 以 = 号对齐是吧，
```
enum {
   A      = 1,  //
   BCD    = 2,  //
}
```
这个等 1 修完就支持。

**Comment by ALL-AC** [comment]
请问最近会打tag吗

**Comment by alingse** [comment]
> 请问最近会打tag吗

还没有彻底解决

1.2.3 修复了语法解析，是原来的正则写的不全面。可以先试试，我试了 go.tag = "json:\"id\"" 这种 ok 了

按等号格式化这个还有点麻烦，还没好。

**Comment by ALL-AC** [comment]
> > 请问最近会打tag吗
> 
> 还没有彻底解决
> 
> 1.2.3 修复了语法解析，是原来的正则写的不全面。可以先试试，我试了 go.tag = "json:"id"" 这种 ok 了
> 
> 按等号格式化这个还有点麻烦，还没好。

好呀，麻烦啦，期待新功能上线！

**Comment by alingse** [comment]
已支持，等我发个小版本。
![截屏2022-11-29 21 32 00](https://user-images.githubusercontent.com/11423310/204542621-0556bf1c-129a-4377-9eff-d39d98d1baaa.png)
![截屏2022-11-29 21 33 32](https://user-images.githubusercontent.com/11423310/204542640-5423853e-89be-4cda-b6f3-99ea6acde208.png)

**Comment by alingse** [comment]
@ALL-AC 1.2.4 可以试试

**Comment by alingse** [comment]
改了几个 API 1.2.5 最新，感觉挺好用的。
